### ISSUE TITLE
Stuck on blocking waiting for file lock under Windows Subsystem for Linux

### ISSUE THREAD

**Issue by toothbrush7777777** [rust-osdev/bootimage#38]
As the title says. Here is the program output (`x64` is the name of my target JSON) when running `cargo xrun`:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s
     Running `cargo bootimage runner target/x64/debug/test01`
Building kernel
    Blocking waiting for file lock on x64's sysroot
```

*.cargo/config*
```toml
[build]
target = "x64.json"

[target.'cfg(target_os = "none")']
runner = "cargo bootimage runner"
```
