### ISSUE TITLE
README lists "target" as a valid option for bootloader package but it is not supported by bootimage

### ISSUE THREAD

**Issue by robert-w-gries** [rust-osdev/bootimage#8]
The README lists `bootloader.target` as a valid option.

```toml
    [package.metadata.bootimage.bootloader]
    name = "bootloader"             # The bootloader crate name
    version = ""                    # The bootloader version that should be used
    git = ""                        # Use the bootloader from this git repository
    branch = ""                     # The git branch to use (defaults to master)
    path = ""                       # Use the bootloader from this local path
    precompiled = false             # Whether the bootloader crate is precompiled
    target = "x86_64-bootloader"    # Target triple for compiling the bootloader
```

### Error

Using the option causes an error.

```
$ bootimage build --target x86_64-rxinu
Error: Config("unexpected `package.metadata.bootimage.bootloader` key `target` with value `\"x86_64-bootloader\"`")
```

### Root Cause

`target` is not included as a valid key here: https://github.com/rust-osdev/bootimage/blob/master/src/config.rs#L58-L71
