### ISSUE TITLE
Error: Failed to find kernel binary in cargo metadata output

### ISSUE THREAD

**Issue by darkdarcool** [rust-osdev/bootimage#93]
I was following the OS tutorial, and ran into an issue when using `cargo bootimage`. 

```
→ cargo bootimage --target ./x64_86-darkos.json                                                                                                                                                                           
Building kernel
   Compiling compiler_builtins v0.1.105
   Compiling core v0.0.0 (C:\Users\ticta\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core)
   Compiling bootloader v0.9.23
   Compiling rustc-std-workspace-core v1.99.0 (C:\Users\ticta\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\rustc-std-workspace-core)
   Compiling os v0.1.0 (C:\Users\ticta\Deno\os)
    Finished dev [unoptimized + debuginfo] target(s) in 21.97s
Error: Failed to find kernel binary in cargo metadata output
```

When looking through to target folder, it did spit out a file that looks to be the kernel binary:
![image](https://github.com/rust-osdev/bootimage/assets/66882633/6932203c-ef6f-4a66-a525-49d893d1978d)

Not exactly sure how to solve this issue. 

My os is Windows (11) and my cargo version is `cargo 1.77.0-nightly (1ae631085 2024-01-17)`

**Comment by darkdarcool** [comment]
Also, my `config.toml` looks like this:

```toml
[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[build]
target = "C:\\Users\\ticta\\Deno\\os\\x64_86-darkos.json"
```
